version: "3"
services:
  mysql:
    image: mysql:8.0.27
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
      - ./initdb.d/mysqld_character.cnf:/etc/mysql/conf.d/mysqld_charset.cnf
    cap_add:
      - SYS_NICE # for suppress error log

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_USER: user
      PMA_PASSWORD: password
    links:
      - mysql
    ports:
      - "4040:80"